name: passport_reader
description: A Flutter package to read passport information using OpenAI GPT-4-o.
version: 0.0.8
homepage: https://github.com/skydheere/passport_reader
repository: https://github.com/skydheere/passport_reader.git
issue_tracker: https://github.com/skydheere/passport_reader/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  http: ^1.2.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.passport_reader
        pluginClass: PassportReaderPlugin
      ios:
        pluginClass: PassportReaderPlugin

  assets:
    - assets/images/pass_scan.gif
# flutter:
 
#   plugin:
#     platforms:
#       android:
#         package: com.example.passport_reader
#         pluginClass: PassportReaderPlugin
#       ios:
#         pluginClass: PassportReaderPlugin
 
 
#   assets:
#     # - assets/images/pass_scan.gif
#     - assets/images/pass_scan.gif
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
